### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Koux99** [Koux99/protospace-36549#1]
#URL
https://protospace-36549.herokuapp.com/

**Comment by takumi0530** [comment]
@Koux99 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザー名の部分が正しく表示されていません。
<img width="588" alt="スクリーンショット 2021-08-13 10 11 51" src="https://user-images.githubusercontent.com/76197191/129291075-bf5ff9f5-e344-4216-9e54-db37cb6383fd.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Koux99** [comment]
@takumi0530  さん、ご確認いただきありがとうございます。
以下修正点に関しまして、修正完了いたしました。
・ユーザー詳細ページの「ユーザー名表示」

ご確認の程よろしくお願いいたします！

#URL
https://protospace-36549.herokuapp.com/

**Comment by takumi0530** [comment]
@Koux99 さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
